### ISSUE TITLE
Install.sh does not work: Filecheck for README is negative

### ISSUE THREAD

**Issue by e-it** [mattanja/automysqlbackup#1]
Starting ./install.sh results in 

README failed

Removing the "README"-Part from install script fixes the problem and the installer works as expected.

**Comment by 45413** [comment]
This is easily resolved without removing the README from the install by modifying the following 3 lines in install.sh:

```
409 README.md b17740fcd3a5f8579b907a42249a83cd
473 cp -i automysqlbackup.conf LICENSE README.md "${configdir}"/
```

Notice the addition of the **.md** extension to the README file.

**Comment by mattanja** [comment]
I have updated the filecheck and removed readme from the check.
